services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tiendaonline
    ports:
      - "3306:3306"
    volumes:
      - /e/Master/TFM/volumenes/mysql:/var/lib/mysql
    networks:
      - springnet

  tienda-app:
    build: ./tiendaonline
    container_name: tiendaapi-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendaonline?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - springnet

  tienda-frontend:
    build:
      context: ./tienda-frontend
    container_name: tienda-container
    ports:
      - "4300:80"
    depends_on:
      - tienda-app
    networks:
      - springnet

  api-images-ubuntu:
    build: ./ApiUbuntuFiles
    container_name: api-ubuntu-container
    ports:
      - "5000:5000"
    volumes:
      - E:/Master/TFM/volumenes/imagenes:/app/uploads   # volumen absoluto del host
    networks:
      - springnet

networks:
  springnet:
    driver: bridge
